--ADD Call trigger IN TABLE llx_c_action_trigger FOR FUNDING MODULE
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_CREATE', 'Funding create', 'A funding is created', '1830040') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_VALIDATE', 'Funding validate', 'A funding is validate', '1830041') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_MODIFY', 'Funding update', 'A funding is updated', '1830042') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_DRAFT', 'Funding DRAFT', 'A funding is DRAFT', '1830043') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_ACCEPT', 'Funding accept', 'A funding is accept by organisation', '1830044') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_DENIED', 'Funding denied', 'A funding is denied by organisation', '1830045') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_SENTBYMAIL', 'Funding send by mail', 'A funding is send by mail', '1830046') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_RUNNING', 'Funding running', 'A funding is running', '1830047') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_END', 'Funding end', 'A funding is end', '1830048') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_CANCEL', 'Funding cancel', 'A funding is cancel', '1830049') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_REOPEN', 'Funding reopen', 'A funding is reopen', '1830050') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_UNVALIDATE', 'Funding unvalidate', 'A funding is unvalidate', '1830051') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_SENDORG', 'Funding send organisme', 'A funding is send to organisme', '1830052') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_LACK', 'Funding lack', 'A funding is lack', '1830053') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_LACKOK', 'Funding lack ok', 'A funding is lack ok', '1830054') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'funding@funding', 'FUNDING_EXTENSION', 'Funding extension', 'A funding is extension', '1830055') ON DUPLICATE KEY UPDATE `elementtype`='funding@funding';

INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'coeficient@funding', 'COEFFICIENT_CREATE', 'Funding coefficient create', 'A funding coefficient is created', '1830071') ON DUPLICATE KEY UPDATE `elementtype`='coeficient@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'coeficient@funding', 'COEFFICIENT_VALIDATE', 'Funding coefficient validate', 'A funding coefficient is validate', '1830071') ON DUPLICATE KEY UPDATE `elementtype`='coeficient@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'coeficient@funding', 'COEFFICIENT_MODIFY', 'Funding coefficient update', 'A funding coefficient is updated', '1830072') ON DUPLICATE KEY UPDATE `elementtype`='coeficient@funding';

INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'retention@funding', 'RETENTION_CREATE', 'Funding retention create', 'A funding retention is created', '1830080') ON DUPLICATE KEY UPDATE `elementtype`='retention@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'retention@funding', 'RETENTION_VALIDATE', 'Funding retention validate', 'A funding retention is validate', '1830081') ON DUPLICATE KEY UPDATE `elementtype`='retention@funding';
INSERT INTO `llx_c_action_trigger` (`rowid`, `elementtype`, `code`, `label`, `description`, `rang`) VALUES (NULL, 'retention@funding', 'RETENTION_MODIFY', 'Funding retention update', 'A funding retention is updated', '1830082') ON DUPLICATE KEY UPDATE `elementtype`='retention@funding';

